# Generated by Django 3.2.6 on 2021-08-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_toppings_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.offer'),
        ),
    ]
